## Interaction 0: POST /charge

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: application/json
```

### Response body recorded for playback (201: application/json):

```
{"charge":"ch_123","status":"paid"}
```

## Interaction 1: GET /balance

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: application/json
```

### Response body recorded for playback (200: application/json):

```
{"balance":4200}
```
