## Interaction 0: GET /weather

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: application/json
```

### Response body recorded for playback (200: application/json):

```
{"city":"London","temp":17}
```

## Interaction 1: GET /weather/forecast

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: application/json
```

### Response body recorded for playback (200: application/json):

```
{"forecast":"rain"}
```
