## Interaction 0: GET /a

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: text/plain
```

### Response body recorded for playback (200: text/plain):

```
body-a
```

## Interaction 1: GET /b

### Request headers recorded for playback:

```
```

### Request body recorded for playback ():

```
```

### Response headers recorded for playback:

```
Content-Type: text/plain
```

### Response body recorded for playback (200: text/plain):

```
body-b
```
